// react/calculator/src/components/calculator/Calculator.tsx
import { useReducer } from "react";
import { CalculatorReducer, CalculatorState } from "../../models/calculator.models";
import { getLastValAndIndxFromArr } from "../../helpers/helpers";
import calculatorReducer from "../../reducers/calculatorReducer";
import css from "./Calculator.module.css";
import Screen from "./Screen";
import Buttons from "./Buttons";

const CALCULATOR_STATE: CalculatorState = { nums: ["0"], operations: [] };


const Calculator = () => {

  const [calc, handleEvt] = useReducer<CalculatorReducer>(calculatorReducer, CALCULATOR_STATE);

  const [ num ] = getLastValAndIndxFromArr<string>(calc.nums);

  return (
    <div className={css.container}>
      <p className={css.title}>CALC</p>
      <Screen value={num} />
      <Buttons onBtnClick={handleEvt} />
    </div>
  )
}

export default Calculator;

// angular/calculator/src/app/calculator/calculator.component.ts
import { Component, OnInit } from '@angular/core';
import { CalculatorService } from './services/calculator.service';

@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.css'],
  providers: [CalculatorService]
})
export class CalculatorComponent implements OnInit {

  nums: string[] = [];
  operations: string[] = [];
  
  constructor(private calculator: CalculatorService) {}

  ngOnInit(): void {
    const { nums, operations } = this.calculator;
    this.nums = nums;
    this.operations = operations;
  }

  handleBtnClick(event: string) {
    this.calculator.handleEvent(event);
  }
}
<div class="container">
  <p class="title">CALC</p>
  <app-screen [value]="nums[nums.length - 1]"></app-screen>
  <app-buttons (onBtnClick)="handleBtnClick($event)"></app-buttons>
</div>
