// react/calculator/src/components/calculator/Buttons.tsx
import { useState, MouseEvent } from "react";
import css from "./Buttons.module.css";

const HIGHLIGHTED_BTNS = {
  "*": false,
  "/": false,
  "+": false,
  "-": false
};

const Buttons = ({ onBtnClick }: { onBtnClick: (operation: string) => void; }) => {

  const [highlightedBtn, setHighlightedBtn] = useState<Record<string, boolean>>(HIGHLIGHTED_BTNS);
  
  const handleBtnClick = (e: MouseEvent<HTMLButtonElement>) => {
    const evt = e.currentTarget.id;
    const newHighlightedBtn = { ...highlightedBtn };
    for (let key in newHighlightedBtn) {
      newHighlightedBtn[key] = key === evt;
    }
    setHighlightedBtn(newHighlightedBtn);
    onBtnClick(evt);
  }
  
  return (
    <div>
      <div className="row">
        <button 
          id="reset"
          className={`${css.btn} ${css['bg-gray']} ${css.black}`} 
          onClick={handleBtnClick}> 
          AC 
        </button>
        <button 
          id="-/+"
          className={`${css.btn} 
          ${css['bg-gray']} ${css.black}`} 
          onClick={handleBtnClick}> 
          <span>+</span>/<span>-</span>
        </button>
        <button 
          id="%"
          className={`${css.btn} ${css["bg-gray"]} ${css.black}`} 
          onClick={handleBtnClick}> 
          % 
        </button>
        <button 
          id="/"
          className={`${css.btn} ${css['bg-orange']} ${highlightedBtn['/'] && css.highlighted}`} 
          onClick={handleBtnClick}> 
          / 
        </button>
      </div>
      <div className="row">
        <button 
          id="7"
          className={`${css.btn} ${css['bg-dark']}`} 
          onClick={handleBtnClick}> 
          7 
        </button>
        <button 
          id="8"
          className={`${css.btn} ${css['bg-dark']}`} 
          onClick={handleBtnClick}> 
          8 
        </button>
        <button 
          id="9"
          className={`${css.btn} ${css['bg-dark']}`} 
          onClick={handleBtnClick}> 
          9 
        </button>
        <button
          id="*" 
          className={`${css.btn} ${css['bg-orange']} ${highlightedBtn['*'] && css.highlighted}`}
          onClick={handleBtnClick}> 
          x 
        </button>
      </div>
      <div className="row">
        <button
          id="4" 
          className={`${css.btn} ${css['bg-dark']}`}
          onClick={handleBtnClick}> 
          4 
        </button>
        <button 
          id="5"
          className={`${css.btn} ${css['bg-dark']}`} 
          onClick={handleBtnClick}> 
          5 
        </button>
        <button 
          id="6"
          className={`${css.btn} ${css['bg-dark']}`} 
          onClick={handleBtnClick}> 
          6 
        </button>
        <button
          id="-" 
          className={`${css.btn} ${css['bg-orange']} ${highlightedBtn['-'] && css.highlighted}`}
          onClick={handleBtnClick}> 
          - 
        </button>
      </div>
    <div className="row">
      <button 
        id="1"
        className={`${css.btn} ${css['bg-dark']}`} 
        onClick={handleBtnClick}> 
        1 
      </button>
      <button 
        id="2"
        className={`${css.btn} ${css['bg-dark']}`} 
        onClick={handleBtnClick}> 
        2 
      </button>
      <button 
        id="3"
        className={`${css.btn} ${css['bg-dark']}`} 
        onClick={handleBtnClick}> 
        3 
      </button>
      <button
        id="+" 
        className={`${css.btn} ${css['bg-orange']} ${highlightedBtn['+'] && css.highlighted}`}
        onClick={handleBtnClick}> 
        + 
      </button>
    </div>
    <div className="row">
      <button 
        id="0"
        className={`${css.btn} ${css['bg-dark']} ${css['btn--wide']}`} 
        onClick={handleBtnClick}> 
        0 
      </button>
      <button 
        id="."
        className={`${css.btn} ${css['bg-dark']}`} 
        onClick={handleBtnClick}> 
        . 
      </button>
      <button
        id="=" 
        className={`${css.btn} ${css['bg-orange']}`} 
        onClick={handleBtnClick}> 
        = 
      </button>
    </div>
  </div>
  )
}

export default Buttons;

// angular/calculator/src/app/calculator/buttons/buttons.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-buttons',
  templateUrl: './buttons.component.html',
  styleUrls: ['./buttons.component.css']
})
export class ButtonsComponent {

  highlightedBtn: Record<string, boolean> = {
    "*": false,
    "/": false,
    "+": false,
    "-": false
  }

  @Output() onBtnClick = new EventEmitter<string>();

  btnClick(val: string) {
    for (let key in this.highlightedBtn) {
      this.highlightedBtn[key] = key === val;
    }
    this.onBtnClick.emit(val);
  }

}

<div>
  <div class="row">
    <button class="btn bg-gray black" (click)="btnClick('reset')" > AC </button>
    <button class="btn bg-gray black" (click)="btnClick('-/+')"> 
      <span>+</span>/<span>-</span>
    </button>
    <button class="btn bg-gray black" (click)="btnClick('%')"> % </button>
    <button 
      class="btn bg-orange" 
      [ngClass]="{'highlighted': highlightedBtn['/']}"
      (click)="btnClick('/')"> 
      / 
    </button>
  </div>
  <div class="row">
    <button class="btn bg-dark" (click)="btnClick('7')"> 7 </button>
    <button class="btn bg-dark" (click)="btnClick('8')"> 8 </button>
    <button class="btn bg-dark" (click)="btnClick('9')"> 9 </button>
    <button 
      class="btn bg-orange"
      [ngClass]="{'highlighted': highlightedBtn['*']}"
      (click)="btnClick('*')"> 
      x 
    </button>
  </div>
  <div class="row">
    <button class="btn bg-dark" (click)="btnClick('4')"> 4 </button>
    <button class="btn bg-dark" (click)="btnClick('5')"> 5 </button>
    <button class="btn bg-dark" (click)="btnClick('6')"> 6 </button>
    <button 
      class="btn bg-orange"
      [ngClass]="{'highlighted': highlightedBtn['/']}"
      (click)="btnClick('-')"> 
      - 
    </button>
  </div>
  <div class="row">
    <button class="btn bg-dark" (click)="btnClick('1')"> 1 </button>
    <button class="btn bg-dark" (click)="btnClick('2')"> 2 </button>
    <button class="btn bg-dark" (click)="btnClick('3')"> 3 </button>
    <button class="btn bg-orange" (click)="btnClick('+')"> + </button>
  </div>
  <div class="row">
    <button class="btn btn--wide bg-dark" (click)="btnClick('0')"> 0 </button>
    <button class="btn bg-dark" (click)="btnClick('.')" > . </button>
    <button class="btn bg-orange" (click)="btnClick('=')"> = </button>
  </div>
</div>
